packages:
  - "playground"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

overrides:
  "@nuxt/kit": "3.21.11"
  nuxt-capo: "link:."

shamefullyHoist: true

strictPeerDependencies: false
